image: registry.znuny.com/znuny/internal/docker-znuny-ci:6.2.2

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - sh /sync_repo.sh git@github.com:znuny/Znuny4OTRS-SecondTicketCreateScreen.git
