image: registry.znuny.com/znuny/internal/docker-otrs6ci:$OTRS_TAG

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - sh /sync_repo.sh git@github.com:znuny/Znuny4OTRS-SecondTicketCreateScreen.git
